swagger: '2.0'
info:
  description: |-
    Inference API for the Finequal Neuronet
  version: 0.0.1
  title: FinEqual inference
  contact:
    name: API Support
    url: https://community.fusionfabric.cloud/index.html
  x-finastra-short-description: Inference API for the Finequal Neuronet
  x-finastra-channel-type: SERVICE
  x-finastra-maturity-level: BETA
  x-finastra-tags:
  x-finastra-audience: RESTRICTED
  x-finastra-implementability: RESTRICTED
  x-finastra-category: Other
  x-finastra-subcategory:  
  x-finastra-icon: Icons_11l.svg
basePath: "/finequal/v1"
schemes:
- https
produces:
- application/json
paths:
  "/inference":
    post:
      tags:
      - Inference
      summary: Infer a mortgage rate from the DNN using the supplied parameters
      description: Infer a mortgage rate from the DNN using the supplied parameters
      operationId: inference
      parameters:
        - in: body
          name: profile
          schema:
            "$ref": "#/definitions/Profile"
      responses:
        '200':
          description: Rate computed
          schema:
            "$ref": "#/definitions/Rate"
  "/cors":
    get:
      responses:
        '200':
          description: AllowOrigin
definitions:
  Profile:
    title: Profile
    description: Profile
    type: object
    properties:
      loanType:
        type: string
        description: type of the loan
        default: CONVENTIONAL
        enum: [CONVENTIONAL, VA_GUARANTEED, FHA_INSURED, FSA_RHS_GUARANTEED]
      purpose:
        type: string
        description: purpose of the loan
        default: PURCHASE
        enum: [REFINANCING, PURCHASE, IMPROVEMENT]
      applicantEthnicity:
        type: string
        description: ethnicity of the applicant
        default: CAUCASIAN
        enum: [HISPANIC_LATINO, CAUCASIAN, AFRICAN_AMERICAN, AMERICAN_INDIAN, ASIAN, HAWAIIAN, NA]
      coApplicantEthnicity:
        type: string
        description: ethnicity of the co-applicant
        default: CAUCASIAN
        enum: [HISPANIC_LATINO, CAUCASIAN, AFRICAN_AMERICAN, AMERICAN_INDIAN, ASIAN, HAWAIIAN, NA]
      applicantGender:
        type: string
        description: gender of the applicant
        default: MALE
        enum: [MALE, FEMALE, NA]
      coApplicantGender:
        type: string
        default: FEMALE
        description: gender of the co-applicant
        enum: [MALE, FEMALE, NA]
      income:
        type: number
        default: 100000
        description: income applicant (in dollars)
      loanAmount:
        type: number
        default: 300000
        description: loan amount (in dollars)
      city:
        type: string
        default: RICHMOND
        description: city of the applicant (for demo purposes)
        enum: [RICHMOND, PARKER, OAK_LEAF, NAPLES]
  Rate:
    title: Rate
    description: Rate
    type: object
    properties:
      rate:
        type: number
        minimum: 0
        maximum: 20
        description: proposed rate of the mortgage